// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dbK-d0tyyR_l3T75YPXy3FLjKvBmuYo',
    appId: '1:978869037890:web:829b6ea9bb7cdc0463f6db',
    messagingSenderId: '978869037890',
    projectId: 'ppg-app-3',
    authDomain: 'ppg-app-3.firebaseapp.com',
    storageBucket: 'ppg-app-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyiVjNeZ5oPipjkXpNGbaRBZV9Y_ja3Y',
    appId: '1:978869037890:android:26bb1e64d41e09dc63f6db',
    messagingSenderId: '978869037890',
    projectId: 'ppg-app-3',
    storageBucket: 'ppg-app-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpddNCNt3R-rZ3vcndEwfT0NF0O6fkWgg',
    appId: '1:978869037890:ios:ebc78e30ca79ca7263f6db',
    messagingSenderId: '978869037890',
    projectId: 'ppg-app-3',
    storageBucket: 'ppg-app-3.firebasestorage.app',
    iosClientId: '978869037890-i7n9087a2k0gnkkcregi320k4t0t7n58.apps.googleusercontent.com',
    iosBundleId: 'com.samess.hyperchatApp',
  );
}
